### ISSUE TITLE
Add tables to Report Summary page

### ISSUE THREAD

**Issue by nathankota** [agrc/ugs-hazards#23]
Table 1 shows mapped geologic hazards, relative severity, and corresponding report pages for hazards that intersect AOI

Table 2 lists other related data (lidar, imagery, etc.) that intersects AOI

**Comment by nathankota** [comment]
Page 2 of https://docs.google.com/document/d/1F7kHj3PBc2DJrQgbNOlHTHLoi9qK-QezcJ_0QzBn97Y/edit

![image](https://user-images.githubusercontent.com/15659642/70077483-2f509080-15be-11ea-8bfb-b08a8b99b439.png)

**Comment by stdavis** [comment]
We don't currently have page numbers. I assume that adding them would be part of this issue as well?

**Comment by nathankota** [comment]
> Are you able to use document.getElementById('elementId').offetHeight or similar to determine when a new page will begin, along with the page dividers?
