### ISSUE TITLE
New Earthquake Hazards Layer

### ISSUE THREAD

**Issue by stdavis** [agrc/ugs-hazards#25]
From Martha Jensen:
>I replaced the Utah Earthquake Hazards layer on AGOL due to symbology issues.  The new URL for the layer is : https://services.arcgis.com/ZzrwjTRez6FJiOq4/arcgis/rest/services/Utah_Earthquake_Hazards_View/FeatureServer
>The item ID is 24b9f6d409c0413b8aa70532ee746e00

**Comment by marthajensen** [comment]
Hello everyone -  I was able to change the Utah Earthquake Hazards back to the old naming convention.   ESRI had a lock on naming the view layer the same thing as the original view layer the other day, but allowed me to name it the 'old' name today.    The new feature service URL is https://services.arcgis.com/ZzrwjTRez6FJiOq4/arcgis/rest/services/Utah_Earthquake_Hazards/FeatureServer          
This should be the same exact feature service URL as the original Earthquake Hazards layer.  The item ID is id=1981a158b7914e9d96740cfdd2d9fb91
Sorry to change the name again!
