### ISSUE TITLE
Add maps to Other Data section

### ISSUE THREAD

**Issue by nathankota** [agrc/ugs-hazards#30]
This section is populated when an AOI intersects Lidar, aerial photography, imagery.

![image](https://user-images.githubusercontent.com/15659642/69727059-fd7f8b80-10de-11ea-9ff4-0d08a4ef2fb4.png)

**Comment by stdavis** [comment]
@nathankota If the AOI doesn't intersect data in the aerial photography centroid or lidar extents layers, do we not show those pages at all?

**Comment by nathankota** [comment]
Those pages should still show even if the AOI doesn't intersect lidar or photography data. In that case, the map will just show the AOI and basemap, and the text remains the same.
