### ISSUE TITLE
Page Numbers in Summary Tables

### ISSUE THREAD

**Issue by nathankota** [agrc/ugs-hazards#42]
> Are you able to use document.getElementById('elementId').offetHeight or similar to determine when a new page will begin, along with the page dividers?

_Originally posted by @nathankota in https://github.com/agrc/ugs-hazards/issues/23#issuecomment-566573817_

**Comment by steveoh** [comment]
Not reliably

**Comment by stdavis** [comment]
I agree with @steveoh's assessment. I don't believe that there is a reliable solution to this request.
