### ISSUE TITLE
Printed text formatting

### ISSUE THREAD

**Issue by nathankota** [agrc/ugs-hazards#43]
> Normal printed text should be 11pt., not 12pt., so the page ends work correctly.

_Originally posted by @nathankota in https://github.com/agrc/ugs-hazards/issues/9#issuecomment-566578693_

**Comment by steveoh** [comment]
I am happy to change the font size. I would be surprised if the page ends and a font size have a correlation. The text is dynamic and will be different for every aoi, so i doubt correctness can be found in a single font size.
