### ISSUE TITLE
Map Scale

### ISSUE THREAD

**Issue by nathankota** [agrc/ugs-hazards#44]
> It would be helpful to have the maps use a scale at a multiple of 2500 or 5000 (such as 1:2500, 1:5000, 1:7500, etc.), so we do not have unusual values.

_Originally posted by @nathankota in https://github.com/agrc/ugs-hazards/issues/21#issuecomment-566576590_

**Comment by steveoh** [comment]
This is the [api](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-ScaleBar.html) we are using. I don't think this request can be satisfied based on the api.

**Comment by stdavis** [comment]
Couldn't we manually snap the map scale to the nearest multiple of 2500?

**Comment by steveoh** [comment]
that's not a bad idea. We could buffer, inspect the scale and then increase to the nearest 2500 increment.

**Comment by stdavis** [comment]
Actually, aren't we pinned at the caching levels? I tried to bump the scale and it's not working.

**Comment by stdavis** [comment]
I don't think that we can satisfy this requirement. The web map is locked into the caching scale levels and I don't see a way of forcing it.
