### ISSUE TITLE
Scale text and scale bars are likely incorrect

### ISSUE THREAD

**Issue by stdavis** [agrc/ugs-hazards#46]
I'm thinking that our scales are likely incorrect since they are based on a map that's [1000x500 pixels](https://github.com/agrc/ugs-hazards/blob/6585494080ddd4bdca94bc5a52582b65d6ecec87/src/reportParts/HazardMap.js#L31). I wonder if there's a way to set the map size to be about what it would be if it was the width of an 8.5 size of paper. Then maybe we would need to add some sort of disclaimer to the report saying that the scales are based on a certain size of paper.

**Comment by steveoh** [comment]
I would rather only display the map scale without the scale bar if there is even a possibility of it being incorrect. I would think we let UGS decide what to do?

**Comment by stdavis** [comment]
If the scale bar is incorrect, then the scale text would be incorrect as well. They are both in the same situation.

**Comment by steveoh** [comment]
I'm not so sure that is true. I thought the scale to which the map is set is fixed no matter what the size of the image. Am I not understanding that properly?

**Comment by nathankota** [comment]
AOI overview map printed scale looks the same as subsequent maps (1:15k), but scale bar is different than those maps, and is identical to the earthquake ground shaking map, which is double the scale value:

AOI:
![image](https://user-images.githubusercontent.com/15659642/71422871-77eded80-2642-11ea-99fa-6a477cfc6c9d.png)
 
Collapsible Soil:
![image](https://user-images.githubusercontent.com/15659642/71422900-a8ce2280-2642-11ea-9adb-a143cb0b7861.png)

Earthquake Ground Shaking:
![image](https://user-images.githubusercontent.com/15659642/71422926-d4e9a380-2642-11ea-9a0e-373c8f71cfde.png)
