### ISSUE TITLE
AOIs with many vertices cause errors

### ISSUE THREAD

**Issue by stdavis** [agrc/ugs-hazards#56]
From @gordondouglass:
![image](https://user-images.githubusercontent.com/1326248/72563796-a8086500-386b-11ea-891a-40221ec4f3a6.png)
![image](https://user-images.githubusercontent.com/1326248/72563813-b22a6380-386b-11ea-9ad6-b01dc58e2f49.png)

The same area works with a more simple polygon:
![image](https://user-images.githubusercontent.com/1326248/72564745-b9eb0780-386d-11ea-82cb-22384bc9ed2d.png)

**Comment by steveoh** [comment]
> UGS decided to limit user input to a size threshold, and likely constrain the shape to a rectangle. I don't know yet if Gordon has experienced the issue when using smaller, simpler polys as AOIs

I'm thinking this is a non issue.

**Comment by stdavis** [comment]
I thought that it was worth recording.

**Comment by jjhi11** [comment]
Yeah I am going to limit the shape to a rectangle. I am curious though if this is a result of the URL length hitting the max?

**Comment by steveoh** [comment]
It'd be a local storage limit since I don't believe we are using the url for the shape transfer.

**Comment by jjhi11** [comment]
Ok

**Comment by stdavis** [comment]
> I am curious though if this is a result of the URL length hitting the max?

I was guessing that this was, indeed, the case when we query the feature layers. I don't think that we are posting that data IIRC.

**Comment by steveoh** [comment]
Ahh, yes, the feature layer queries... that would definitely put the shape in the url. We can certainly switch to posting, but if you are restricting the # of vertices then we should be ok.
