### ISSUE TITLE
Map Image Size

### ISSUE THREAD

**Issue by stdavis** [agrc/ugs-hazards#9]
Right now the map image size is hardcoded. The div is `1000x500` and the image size is set to `100%` width and a min-height of `200px`. I wonder if this should be optimized for printing on a letter-sized paper.

**Comment by steveoh** [comment]
from https://www.docucopies.com/image-resolution/ it sounds like we want very good is 2550, excellent is 3400

**Comment by nathankota** [comment]
> Normal printed text should be 11pt., not 12pt., so the page ends work correctly.
